# Generated by Django 6.0.3 on 2026-05-14 16:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_templates',
            field=models.JSONField(blank=True, default=users.models.default_email_templates),
        ),
        migrations.AddField(
            model_name='company',
            name='hiring_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_stages',
            field=models.JSONField(blank=True, default=users.models.default_interview_stages),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
